// 계산 결과 키 → 한국어 라벨 (GenericCalculator · 표 · 가이드 공용)
export const OUTPUT_LABELS: Record<string, string> = {
  // 2026-09-03 화면 교체 때 발견된 누락 라벨
  grandTotal: "근로자 + 회사 합계",
  employeeHI: "근로자 건강보험",
  employeeLTC: "근로자 장기요양",
  employeeTotal: "근로자 부담 합계",
  employerHI: "사업주 건강보험",
  employerLTC: "사업주 장기요양",
  employerWC: "사업주 산재보험",
  employerTotal: "사업주 부담 합계",
  deductRatePct: "공제율",
  median48: "중위 48%",
  median32: "중위 32%",
  phase3Monthly: "3단계 월액",
  discountRate: "연납 공제율",
  autoTax: "자동차세",
  eduTax: "지방교육세",
  termDays: "재직 일수",
  sumday: "퇴사 전 3개월 일수",
  absoluteCap: "절대 한도",
  P: "기본연금액",
  standardCredit: "표준세액공제",
  // ltv/대출 — 누락분
  leaseDeductTotal: "임차보증금 공제",
  priorityClaim: "최우선변제 한도",
  feePct: "수수료율",
  rateInRange: "약정 범위 내",
  // 모드/구분
  mode: "상환방식",
  accountType: "ISA 유형",
  taxFree: "비과세 적용",
  category: "주택보유 상태",
  regionType: "지역 구분",
  area: "소액보증금 지역",
  roomDeduction: "방 공제",
  stressDSR: "스트레스 DSR",
  appliedRate: "적용 금리",
  // 급여 / 4대보험
  netMonthly: "월 실수령액",
  grossMonthly: "월 세전 급여",
  monthly: "월 환산",
  totalDeduction: "총 공제액",
  totalInsurance: "4대보험 합계",
  nationalPension: "국민연금",
  np: "국민연금",
  healthInsurance: "건강보험",
  hi: "건강보험",
  longTermCare: "장기요양보험",
  ltc: "장기요양보험",
  employmentInsurance: "고용보험",
  ei: "고용보험",
  wc: "산재보험",
  employeeNP: "근로자 국민연금",
  employerNP: "사업주 국민연금",
  employeeEI: "근로자 고용보험",
  employerEI: "사업주 고용보험",
  employee: "근로자 부담",
  employer: "사업주 부담",
  companyPay: "회사 부담",
  selfPay: "본인 부담",
  // 소득세 / 세액
  monthlyIncomeTax: "소득세 (월)",
  monthlyLocalTax: "지방소득세 (월)",
  annualIncomeTax: "연 소득세",
  totalIncomeTax: "총 소득세",
  incomeTax: "소득세",
  taxBeforeCredit: "산출세액",
  taxBeforeLocal: "결정세액 (지방세 전)",
  taxBeforeSeniorDed: "공제 전 세액",
  seniorDed: "고령자 공제",
  taxableIncome: "과세표준",
  taxable: "과세표준",
  taxableBase: "과세표준",
  taxableGain: "양도차익",
  earnedIncomeDeduction: "근로소득공제",
  personalDeduction: "인적공제",
  spouseDeduction: "배우자 공제",
  funeral: "장례비용 공제",
  appliedSalary: "산정 기준 통상임금 (최저임금 하한 적용)",
  homes: "주택 수",
  totalValue: "공시가격 합계",
  isOneHome: "1세대 1주택",
  ratePct: "적용 세율 (%)",
  heavy: "중과세율 적용",
  taxBeforePropertyCredit: "재산세공제 전 종부세",
  propertyTaxCredit: "공제할 재산세액",
  calcTax: "산출세액",
  ageCredit: "고령자 세액공제",
  holdingCredit: "장기보유 세액공제",
  creditTotal: "세액공제 합계 (80% 한도)",
  compPayable: "종부세 납부액 (농특세 포함)",
  propertyTaxTotal: "재산세 합계",
  taxableValue: "과세가액",
  filingCredit: "신고세액공제 (3%)",
  payableTax: "납부할 세액",
  incomeTax100: "간이세액표 소득세 (100%)",
  childAdjust: "자녀 조정 차감",
  earnedIncomeCredit: "근로소득세액공제",
  childCredit: "자녀세액공제",
  newbornCredit: "출산입양 공제",
  taxCredit: "세액공제",
  regularCredit: "기본 공제",
  decisionTax: "결정세액",
  localTax: "지방소득세",
  totalTax: "총 세금",
  marginalRate: "한계세율",
  taxRate: "세율",
  rate: "요율",
  baseRate: "기본 요율",
  ltbcRate: "장기보유특별공제율",
  reductionRate: "감면율",
  // 부동산 세금
  acquisitionTax: "취득세",
  registrationTax: "등록면허세",
  brokerageFee: "중개수수료",
  totalFee: "총 수수료",
  vat: "부가세",
  educationTax: "교육세",
  ruralTax: "농어촌특별세",
  propertyTax: "재산세",
  propertyEduTax: "지방교육세",
  compTax: "종합부동산세",
  generalTax: "일반세",
  transferTax: "양도세",
  longTermDeduction: "장기보유특별공제",
  yearsDed: "보유기간 공제",
  // 대출 / 금융
  monthlyPayment: "월 상환액",
  monthlyInterest: "월 이자",
  totalInterest: "총 이자",
  totalPayment: "총 상환액",
  totalRepayment: "총 상환액",
  maxLoan: "최대 대출 한도",
  depositRatio: "대출 가능 금액 (보증금 × 보증비율)",
  appliedLimit: "적용 한도 (보증한도 cap 적용)",
  ltvLimit: "LTV 한도",
  dsrLimitAmount: "DSR 한도 금액",
  dsrPct: "DSR",
  dtiPct: "DTI",
  ltvPct: "LTV",
  ltv: "LTV",
  graceMonthlyInterest: "거치 월 이자",
  totalGraceInterest: "거치기간 총 이자",
  phase1Monthly: "1단계 월액",
  phase2Monthly: "2단계 월액",
  newMonthly: "신규 월 상환",
  oldMonthly: "기존 월 상환",
  newTotal: "신규 총 상환",
  oldTotal: "기존 총 상환",
  diff: "차액",
  savings: "절감액",
  fee: "수수료",
  // 저축 / 만기
  maturityAmount: "만기 수령액",
  maturity: "만기액",
  compoundMaturity: "복리 만기",
  simpleMaturity: "단리 만기",
  totalDeposit: "총 납입액",
  totalContribution: "총 납입액",
  annualContribution: "연 납입액",
  monthlyContribution: "월 납입액",
  monthlyMatching: "월 매칭금",
  matchingTotal: "정부 기여금",
  govPay: "정부 지원금",
  ownTotal: "본인 납입",
  expectedBalance: "예상 잔액",
  totalNet: "세후 합계",
  netPayment: "세후 지급액",
  taxOnInterest: "이자소득세",
  netInterest: "세후 이자",
  interest: "이자",
  simpleInterest: "단리 이자",
  compoundInterest: "복리 이자",
  isaTax: "ISA 세금",
  taxSaving: "절세액",
  // 연금
  monthlyPension: "월 연금액",
  yearlyPension: "연 연금액",
  annualPension: "연 연금액",
  reducedPension: "감액 연금",
  yearsEarly: "조기수령 연수",
  dbAmount: "DB형 퇴직금",
  // 실업급여
  benefitDays: "수급 가능 일수",
  dailyBenefit: "일 수급액",
  totalBenefit: "총 수급액",
  rawBenefit: "기본 수급액",
  rawDailyWage: "평균임금",
  avgDailyWage: "평균임금",
  dailyAvgWage: "일평균임금",
  remainingDays: "잔여 일수",
  // 자격 판정
  isEligible: "자격",
  isExpired: "기한 경과",
  isNonTaxable: "비과세 여부",
  applied: "적용 여부",
  appliedAmount: "적용 금액",
  // 법률
  childSupport: "월 양육비",
  alimony: "위자료 예상액",
  severancePay: "퇴직금",
  severance: "퇴직금",
  hourlyWage: "시급",
  netDailyWage: "세후 일급",
  dailyTax: "일 소득세",
  dailyLocalTax: "일 지방세",
  totalDailyDeduct: "일 공제 합계",
  unpaidAmount: "미지급 금액",
  nonCustodianShare: "비양육자 부담 비율",
  standardSupport: "표준양육비",
  // 상속 / 증여
  inheritanceTax: "상속세",
  giftTax: "증여세",
  spouse: "배우자",
  child: "자녀",
  parent: "부모",
  sibling: "형제",
  // 부동산 수익
  rentalYield: "임대수익률",
  grossYieldPct: "표면수익률",
  netYieldPct: "실질수익률",
  monthlyRent: "월세",
  baseRent: "기본 임대료",
  jeonseEquivalent: "전세 환산",
  conversionAmount: "전월세 전환",
  annualRentIncome: "연 임대소득",
  netCost: "순 비용",
  netLoss: "순 손실",
  totalBuyCost: "총 매수 비용",
  totalJeonseCost: "총 전세 비용",
  totalCollegeCost: "총 대학 등록금",
  futureTuition: "미래 등록금",
  yearsToCollege: "대학 진학까지 연수",
  monthlyNeeded: "월 필요액",
  monthlySaving: "월 저축액",
  totalROI: "총 수익률",
  annualROI: "연 수익률",
  investedCapital: "투자 자본",
  profit: "수익",
  gain: "이익",
  // 정부지원금 / 복지
  livelihood: "생계급여",
  livelihoodBase: "생계급여 기준",
  medical: "의료급여",
  housing: "주거급여",
  education: "교육급여",
  median30: "중위 30%",
  median40: "중위 40%",
  median47: "중위 47%",
  median50: "중위 50%",
  median100: "중위 100%",
  threshold: "기준액",
  incomeAmount: "소득인정액",
  incomePct: "소득 백분위",
  monthlySupport: "월 지원금",
  annualSupport: "연 지원금",
  monthlyAvailable: "월 수령 가능",
  monthlyAvail: "월 수령 가능",
  parentalAllowance0: "부모급여 0세",
  parentalAllowance1: "부모급여 1세",
  childAllowance: "아동수당",
  newLevel: "변경 단계",
  tier: "단계",
  estimatedAmount: "예상 금액",
  // 보험
  monthlyPremium: "월 보험료",
  annualPremium: "연 보험료",
  adjustedPremium: "조정 보험료",
  ageMultiplier: "연령 배수",
  faultMultiplier: "할증 배수",
  ageGroup: "연령 그룹",
  reimbursement: "환급금",
  surrender: "해지환급금",
  payable: "지급액",
  surcharge: "할증료",
  // 청약
  totalPoints: "총 가점",
  noHomeOk: "무주택 자격",
  noHomeScore: "무주택 가점",
  accountOk: "통장 자격",
  accountScore: "통장 가점",
  familyScore: "부양가족 가점",
  depositOk: "납입 자격",
  // 시뮬레이션
  totalCost: "총 비용",
  totalSaving: "총 저축",
  totalPaid: "총 납부",
  totalPay: "총 지급",
  totalReturn: "총 환급",
  total: "총계",
  furniture: "가구",
  wedding: "예식",
  incentive: "인센티브",
  fundNet: "펀드 순수익",
  fixedNet: "예금 순수익",
  savingsNet: "적금 순수익",
  // 일반 / 기타
  refund: "환급액",
  expense: "지출",
  baseAmount: "기준 금액",
  baseTax: "기준 세액",
  principal: "원금",
  excess: "초과액",
  limit: "한도",
  maxAmount: "한도액",
  result: "결과",
  amount: "금액",
  // 날짜 / 기간
  days: "일수",
  months: "개월수",
  years: "연수",
  totalDays: "총 일수",
  threeMonthTotal: "3개월 합계",
  westAge: "만나이",
  koreanAge: "한국나이",
  zodiac: "띠",
  deadline: "기한",
  firstMeeting: "최초 면담일",
  firstPayment: "첫 달 상환",
  lastPayment: "마지막 달 상환",
  repayMonthly: "월 상환금",
  // 미분류
  netAnnualIncome: "연 순소득",
  discountRatePct: "할인율 (%)",
  userPct: "사용자 비율 (%)",
  year: "연도",
  support: "지원금",
  allowance: "수당",
  dailyWage: "일급",
  deduction: "공제액",
  tax: "세금",
  monthlyAvg: "월 평균",
  annualConverted: "연 환산",
};
