// 자동 생성: scripts/migrate-hub-urls.mjs 의 매핑(scripts/url-map.json) — 직접 수정하지 말 것
// 주제 허브 주소. 계산기와 총정리 글이 한 페이지에 있고, 스포크는 그 하위 디렉토리로 들어간다.
export const HUB: Record<string, string> = {
  "government/unemployment-benefit": "unemployment",
  "government/basic-pension": "basic-pension",
  "government/basic-livelihood-eligibility": "basic-livelihood",
  "government/parental-leave-pay": "parental-leave",
  "government/maternity-leave-pay": "maternity",
  "government/earned-income-tax-credit": "eitc",
  "government/industrial-accident-pay": "injury-pay",
  "government/median-income": "median-income",
  "government/national-scholarship": "scholarship",
  "government/near-poor-eligibility": "near-poor",
  "government/single-parent-support": "single-parent",
  "law/severance-pay": "severance",
  "law/annual-leave-allowance": "annual-leave",
  "law/unpaid-wages": "unpaid-wages",
  "law/child-support": "child-support",
  "law/divorce-alimony": "alimony",
  "law/inheritance-share": "inheritance-share",
  "tax/salary-net-pay": "salary",
  "tax/comprehensive-income-tax": "income-tax",
  "tax/four-major-insurance": "four-insurance",
  "tax/freelancer-tax": "freelancer",
  "tax/retirement-income-tax": "retirement-tax",
  "tax/business-income-tax-simple": "business-income-tax",
  "tax/child-tax-credit": "child-credit",
  "tax/crypto-transfer-tax": "crypto-tax",
  "tax/daily-wage-tax": "daily-wage",
  "tax/gift-tax": "gift-tax",
  "tax/inheritance-tax": "inheritance-tax",
  "tax/other-income-tax": "other-income",
  "tax/stock-transfer-tax": "stock-tax",
  "tax/vat-general": "vat",
  "tax/vat-simplified": "vat-simple",
  "realestate/acquisition-tax": "acquisition-tax",
  "realestate/transfer-tax": "transfer-tax",
  "realestate/property-tax": "property-tax",
  "realestate/comprehensive-real-estate-tax": "comprehensive-tax",
  "realestate/holding-tax-total": "holding-tax",
  "realestate/brokerage-fee": "brokerage",
  "realestate/housing-subscription-score": "subscription-score",
  "realestate/jeonse-monthly-conversion": "jeonse-conversion",
  "realestate/real-estate-roi": "roi",
  "realestate/rental-yield": "rental-yield",
  "loan/dsr-limit": "dsr",
  "loan/dti-limit": "dti",
  "loan/ltv-limit": "ltv",
  "loan/mortgage-loan-limit": "mortgage",
  "loan/credit-loan": "credit-loan",
  "loan/jeonse-loan": "jeonse-loan",
  "loan/loan-amortization": "repayment",
  "loan/loan-refinance": "refinance",
  "loan/prepayment-fee": "prepayment",
  "pension/national-pension": "national-pension",
  "pension/national-pension-early": "pension-early",
  "pension/irp-tax-credit": "irp",
  "pension/noranumbrella-tax-saving": "noranumbrella",
  "savings/installment-savings": "installment",
  "savings/fixed-deposit": "deposit",
  "savings/free-savings": "free-savings",
  "savings/isa-tax-saving": "isa",
  "savings/tax-free-savings": "tax-free-savings",
  "insurance/auto-tax": "auto-tax",
  "insurance/medical-insurance-payout": "medical-payout",
  "util/age-calculator": "age",
  "util/date-calculator": "date",
  "util/percent-calculator": "percent",
  "util/cash-service-fee": "cash-service",
  "util/installment-fee": "card-installment"
};

/** "law/severance-pay" → "/severance/" (매핑이 없으면 옛 주소를 그대로 쓴다) */
export const hubHref = (cat: string, slug: string) => {
  const h = HUB[cat + "/" + slug];
  return h ? `/${h}/` : `/${cat}/${slug}/`;
};
